bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (  # index,
    BbIndexView, BbMonthView, BbByRubricView,
    BbCreateView, BbDetailView, BbEditView, BbDeleteView,
    BbRedirectView, edit, add_save, rubrics, bbs, search)


app_name = 'bboard'

urlpatterns = [
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/save/', add_save, name='add_save'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('update/<int:pk>/', BbEditView.as_view(), name='update'),
    # path('update/<int:pk>/', edit, name='update'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),

    # path('', index, name='index'),
    path('', BbIndexView.as_view(), name='index'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('search/', search, name='search'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('testapp.urls', namespace='test')),
    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

templates/includes/inc_main_menu.html
<nav>
    <a href="{% url 'bboard:index' %}">Главная</a>
{#    {% if 'bboard.add_bb' in perms %}#}
    {% if perms.bboard.add_bb %}
        <a href="{% url 'bboard:add' %}">Добавить</a>
    {% else %}
        <a href="{% url 'bboard:login' %}" class="text-danger">Войти</a>
    {% endif %}
{#{{ rubrics.0 }}#}
    {% for rubric in rubrics %}
        {% with bb_count=rubric.cnt %}
        <a href="{{ rubric.get_absolute_url }}">
{#            {{ rubric.name }} ({{ rubric.cnt }})</a>#}
            {% filter upper %}
                {{ rubric.name }}
            {% endfilter %}
            ({{ bb_count }})</a>
        {% endwith %}
    {% endfor %}
</nav>

templates/includes/inc_paginator.html
{#    <div>#}
{#        {% if page.has_previous %}#}
{#            <a href="?page={{ page.previous_page_number }}">&lt;</a>#}
{#            &nbsp; &nbsp; | &nbsp; &nbsp;#}
{#        {% endif %}#}
{##}
{#        Страница №{{ page.number }} из {{ page.paginator.num_pages }}#}
{##}
{#        {% if page.has_next %}#}
{#            &nbsp; &nbsp; | &nbsp; &nbsp;#}
{#            <a href="?page={{ page.next_page_number }}">&gt;</a>#}
{#        {% endif %}#}
{#    </div>#}

{% if page_obj.has_other_pages %}
    <nav aria-label="pagination">
        <ul class="pagination">

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
            {% endif %}
        
            {% for p in page_obj.paginator.page_range %}
                {% if not p == page_obj.number %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link disabled bg-primary text-light"
                       href="?page={{ p }}">{{ p }}</a>
                </li>
                {% endif %}
            {% endfor %}
        
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.next_page_number }}">Вперёд</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}