bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (  # index,
    BbIndexView, BbMonthView, BbByRubricView,
    BbCreateView, BbDetailView, BbEditView, BbDeleteView,
    BbRedirectView, edit, add_save, rubrics, bbs, search)


app_name = 'bboard'

urlpatterns = [
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/save/', add_save, name='add_save'),
    path('add/', BbCreateView.as_view(), name='add'),
    path('update/<int:pk>/', BbEditView.as_view(), name='update'),
    # path('update/<int:pk>/', edit, name='update'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),

    # path('', index, name='index'),
    path('', BbIndexView.as_view(), name='index'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('search/', search, name='search'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('testapp.urls', namespace='test')),
    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

templates/bb_detail.html
[% extends 'layout/basic.html' %]

{% block title %}{{bb.title}}{% endblock %}

{% block content %}
    <p> Рубрика: {{ bb.rubric.name }}</p>
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p> Цена: {{bb.price}} </p>
{% endblock %}

templates/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}
<h2>Рубрика: {{ current_rubric.name }}</h2>

{% for bb in bbs %}
<div>
    <h2>
        <a href="{% url 'bboard:detail' pk=bb.pk %}">
            {{ bb.title }}</a>
    </h2>
    <p>{{ bb.content }}</p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}

{% endblock %}

templates/create.html
{% extends "layout/basic.html" %}

{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>
    
{% if form.is_multipart %}
    <form method="post" enctype="multipart/form-data">
{% else %}
    <form method="post">
{% endif %}
    {% csrf_token %}
{#    {{ form.as_p }}#}
{#    <ul>#}
{#            {{ form.as_ul }}#}
{#    </ul>#}
    <table>
{#        {{ form.as_table }}#}
        {{ form }}
    </table>
{#    <input type="submit" value="Добавить">#}

    <button type="submit" class="btn btn-primary">Добавить</button>

</form>
{% endblock %}

templates/data_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>API Data</title>
</head>
<body>
    <h1>Data from Fake API</h1>
    <ul>
        {% for item in data %}
            <li>User ID: {{ item.userId }}, ID: {{ item.id }}, Title: {{ item.title }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f8f9fa;
            padding-top: 50px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Текст</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="index.html">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="login.html">Вход</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h2>Главная страница</h2>
        <p>Текст.</p>
    </div>
</body>
</html>

templates/index.html
{% extends "layout/basic.html" %}

{% block content %}
    
{% for bb in bbs %}
<div>
    <h2>
        <a href="{% url 'bboard:detail' bb.pk %}">
{#            {{ forloop.counter0|add:page.start_index }} - {{ bb.title_and_price }}</a>#}
            {{ forloop.counter0|add:page_obj.start_index }} - {{ bb.title_and_price }}</a>
    </h2>
    <p>{{ bb.content }}</p>
    <p>
        <a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
            {{ bb.rubric.name }}</a>
    </p>

    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>

</div>
{% empty %}
    <p>Объявлений нет!!!</p>
{% endfor %}
    
{% include 'includes/inc_paginator.html' %}
{#{% include 'includes/inc_paginator_cbv.html' %}#}
    
{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="samplesite\static\css\login_and_home.css">
</head>

<body>
    <div class="login-container">
        <h2>Вход</h2>
        <form>
            <div class="form-group">
                <label for="username">Имя пользователя</label>
                <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя">
            </div>
            <div class="form-group">
                <label for="password">Пароль</label>
                <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль">
            </div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
    </div>
</body>

</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>{{ title }}</h1>
{% for bb in bbs %}
    <p>{{ bb }}</p>
{% endfor %}


<h2>{{ res }}</h2>
<h3>{{ res.url_name }}</h3>
<h3>{{ res.view_name }}</h3>

</body>
</html>